version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: /bin/sh
    environment:
      GOPATH: /go/
      username: test
      password: test
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
